name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.6"

      - run: |
          ./cli link --url $PROD_DB_URL
          ./cli deploy
        env:
          PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
