name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'

      - run: |
          curl -sL https://github.com/soedirgo/cli/releases/download/v0.10.8/supabase_0.10.8_linux_amd64.tar.gz > supabase.tar.gz
          tar -xzf supabase.tar.gz
          chmod +x ./supabase
          ./supabase link --url $PROD_DB_URL
          ./supabase deploy
        env:
          PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
