name: Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          curl -sSL "https://github.com/supabase/cli/releases/download/v0.31.2/supabase_0.31.2_linux_amd64.tar.gz" | tar -xz
          chmod +x ./supabase
          ./supabase db remote set ${{ secrets.STAGING_DB_URL }}
          ./supabase db push
